const quiz_cyberlaw = [];
const cyberlawTemplates = [
    { q: "UU ITE di Indonesia diatur dalam undang-undang nomor berapa?", opts: ["UU No. 11 Tahun 2008", "UU No. 19 Tahun 2016", "UU No. 27 Tahun 2022", "UU No. 36 Tahun 1999"], ans: 0, exps: ["BENAR. UU No. 11 Tahun 2008 adalah UU ITE pertama yang mengatur Informasi dan Transaksi Elektronik di Indonesia.", "UU No. 19 Tahun 2016 adalah PERUBAHAN (revisi pertama) atas UU ITE, bukan UU ITE asli.", "UU No. 27 Tahun 2022 adalah UU Pelindungan Data Pribadi (UU PDP), bukan UU ITE.", "UU No. 36 Tahun 1999 adalah UU Telekomunikasi."] },
    { q: "Pasal berapa dalam UU ITE yang mengatur tentang akses ilegal (unauthorized access)?", opts: ["Pasal 27", "Pasal 28", "Pasal 30", "Pasal 35"], ans: 2, exps: ["Pasal 27 mengatur tentang konten yang dilarang (kesusilaan, perjudian, pencemaran nama baik, pemerasan).", "Pasal 28 mengatur tentang penyebaran berita bohong dan informasi SARA.", "BENAR. Pasal 30 UU ITE mengatur tentang akses ilegal: ayat (1) tanpa hak, (2) untuk memperoleh data, (3) dengan menembus pengamanan.", "Pasal 35 mengatur tentang manipulasi/pemalsuan informasi elektronik."] },
    { q: "Apa sanksi maksimal untuk pelanggaran Pasal 30 ayat (3) UU ITE (menembus sistem pengamanan)?", opts: ["4 tahun penjara", "6 tahun penjara", "8 tahun penjara", "12 tahun penjara"], ans: 2, exps: ["4 tahun bukan sanksi untuk Pasal 30 ayat (3).", "6 tahun adalah sanksi untuk Pasal 30 ayat (1), akses tanpa hak saja.", "BENAR. Pasal 46 ayat (3) menyatakan sanksi untuk Pasal 30 ayat (3) adalah penjara maksimal 8 tahun dan/atau denda Rp800 juta.", "12 tahun adalah sanksi untuk Pasal 36 (perbuatan yang mengakibatkan kerugian)."] },
    { q: "UU Pelindungan Data Pribadi (UU PDP) diatur dalam undang-undang nomor berapa?", opts: ["UU No. 11 Tahun 2008", "UU No. 19 Tahun 2016", "UU No. 27 Tahun 2022", "UU No. 1 Tahun 2024"], ans: 2, exps: ["UU No. 11/2008 adalah UU ITE.", "UU No. 19/2016 adalah revisi pertama UU ITE.", "BENAR. UU No. 27 Tahun 2022 tentang Pelindungan Data Pribadi (UU PDP).", "UU No. 1/2024 adalah revisi kedua UU ITE."] },
    { q: "Manakah yang BUKAN termasuk karakteristik unik ruang cyber (cyberspace)?", opts: ["Borderless (tanpa batas)", "Anonimitas pengguna", "Bersifat tangible (berwujud)", "Real-time"], ans: 2, exps: ["Borderless memang karakteristik cyberspace — internet tidak mengenal batas negara.", "Anonimitas memang karakteristik cyberspace — pengguna bisa menyembunyikan identitas.", "BENAR. Cyberspace bersifat INTANGIBLE (tidak berwujud), bukan tangible.", "Real-time memang karakteristik cyberspace — aktivitas terjadi secara instan."] },
    { q: "Pasal 27 ayat (3) UU ITE mengatur tentang apa?", opts: ["Penyebaran konten asusila", "Perjudian online", "Pencemaran nama baik", "Pemerasan elektronik"], ans: 2, exps: ["Konten asusila diatur di Pasal 27 ayat (1).", "Perjudian online diatur di Pasal 27 ayat (2).", "BENAR. Pasal 27 ayat (3) mengatur tentang pencemaran nama baik melalui media elektronik.", "Pemerasan elektronik diatur di Pasal 27 ayat (4)."] },
    { q: "Kasus Prita Mulyasari vs RS Omni International berkaitan dengan pasal apa?", opts: ["Pasal 27 ayat (1) — konten asusila", "Pasal 27 ayat (3) — pencemaran nama baik", "Pasal 28 ayat (1) — berita bohong", "Pasal 30 — akses ilegal"], ans: 1, exps: ["Kasus Prita bukan tentang konten asusila.", "BENAR. Prita digugat oleh RS Omni dengan Pasal 27 ayat (3) karena menulis email keluhan yang dianggap pencemaran nama baik.", "Kasus Prita bukan tentang berita bohong, melainkan keluhan konsumen.", "Prita tidak melakukan akses ilegal ke sistem komputer."] },
    { q: "Apa hasil akhir kasus Prita Mulyasari di Mahkamah Agung?", opts: ["Dihukum 6 bulan penjara", "Dihukum denda Rp200 juta", "DIBEBASKAN", "Kasus dihentikan"], ans: 2, exps: ["Prita pernah divonis di tingkat PN, tapi keputusan ini dibatalkan oleh MA.", "Tidak ada putusan denda dari MA.", "BENAR. MA membebaskan Prita (2012), menyatakan keluhan konsumen yang bonafide dilindungi hukum.", "Kasus tidak dihentikan, tapi diputus oleh MA."] },
    { q: "Pasal 28J ayat (2) UUD 1945 mengatur tentang apa?", opts: ["Kebebasan berekspresi tanpa batas", "Pembatasan hak untuk menghormati hak orang lain", "Hak atas informasi", "Hak atas perlindungan data"], ans: 1, exps: ["Kebebasan berekspresi diatur di Pasal 28E dan tidak tanpa batas.", "BENAR. Pasal 28J(2) menyatakan setiap orang wajib tunduk kepada pembatasan UU untuk menjamin penghormatan hak orang lain.", "Hak atas informasi diatur di Pasal 28F.", "Hak atas perlindungan diri diatur di Pasal 28G."] },
    { q: "Berapa jangka waktu kewajiban notifikasi data breach menurut UU PDP?", opts: ["1 x 24 jam", "3 x 24 jam", "7 x 24 jam", "14 x 24 jam"], ans: 1, exps: ["1 x 24 jam terlalu singkat menurut UU PDP.", "BENAR. UU PDP Pasal 46 mewajibkan notifikasi data breach paling lambat 3 x 24 jam.", "7 hari bukan ketentuan UU PDP.", "14 hari bukan ketentuan UU PDP."] },
    { q: "Manakah yang termasuk Data Pribadi Spesifik menurut UU PDP?", opts: ["Nama lengkap", "Alamat email", "Data kesehatan", "Nomor telepon"], ans: 2, exps: ["Nama lengkap termasuk data pribadi UMUM.", "Alamat email termasuk data pribadi UMUM.", "BENAR. Data kesehatan termasuk Data Pribadi Spesifik yang mendapat perlindungan lebih ketat.", "Nomor telepon termasuk data pribadi UMUM."] },
    { q: "Apa yang dimaksud dengan 'effects doctrine' dalam hukum cyber?", opts: ["Hukum berlaku di tempat pelaku", "Hukum berlaku di tempat server", "Hukum berlaku di tempat DAMPAK dirasakan", "Hukum berlaku secara universal"], ans: 2, exps: ["Itu adalah prinsip asas teritorial, bukan effects doctrine.", "Lokasi server bukan penentu yurisdiksi dalam effects doctrine.", "BENAR. Effects doctrine berarti hukum berlaku jika dampak perbuatan dirasakan di negara tersebut. UU ITE Pasal 2 menerapkan ini.", "Itu adalah prinsip universalitas, berbeda dari effects doctrine."] },
    { q: "Setelah revisi UU ITE (UU 1/2024), Pasal 27 ayat (3) berubah menjadi?", opts: ["Dihapus sepenuhnya", "Tetap delik biasa", "Menjadi delik aduan", "Menjadi delik materiil"], ans: 2, exps: ["Pasal 27(3) tidak dihapus, hanya direvisi.", "Sebelum revisi memang delik biasa, tapi setelah revisi berubah.", "BENAR. Setelah revisi, Pasal 27(3) berubah menjadi DELIK ADUAN — polisi hanya menyelidiki jika ada pengaduan korban.", "Delik materiil adalah konsep yang berbeda."] },
    { q: "PP 71/2019 mengatur tentang apa?", opts: ["Pelindungan Data Pribadi", "Penyelenggaraan Sistem dan Transaksi Elektronik", "Perdagangan Elektronik", "Telekomunikasi"], ans: 1, exps: ["Pelindungan Data Pribadi diatur oleh UU No. 27/2022.", "BENAR. PP No. 71 Tahun 2019 mengatur tentang Penyelenggaraan Sistem dan Transaksi Elektronik (PSTE).", "Perdagangan elektronik diatur PP 80/2019.", "Telekomunikasi diatur UU 36/1999."] },
    { q: "Jika mantan karyawan IT mengakses sistem perusahaan setelah resign, pasal apa yang paling tepat?", opts: ["Pasal 27 — konten terlarang", "Pasal 28 — berita bohong", "Pasal 30 — akses ilegal", "Pasal 35 — manipulasi data"], ans: 2, exps: ["Pasal 27 tentang konten, bukan akses sistem.", "Pasal 28 tentang berita bohong/SARA.", "BENAR. Pasal 30 ayat (1) mengatur akses TANPA HAK ke sistem elektronik. Mantan karyawan yang resign tidak lagi memiliki hak akses.", "Pasal 35 tentang pemalsuan informasi, bukan akses ilegal."] },
    { q: "Apa perbedaan utama jalur hukum pidana dan perdata dalam kasus cyber?", opts: ["Pidana menghukum pelaku, Perdata ganti rugi", "Tidak ada perbedaan", "Pidana untuk perusahaan, Perdata untuk individu", "Pidana lebih cepat"], ans: 0, exps: ["BENAR. Jalur PIDANA bertujuan menghukum pelaku (penjara/denda), PERDATA bertujuan mendapatkan kompensasi/ganti rugi.", "Ada perbedaan signifikan.", "Keduanya bisa untuk individu maupun perusahaan.", "Kecepatan bervariasi per kasus."] },
    { q: "Apa yang dimaksud dengan 'Right to be Forgotten'?", opts: ["Hak menggunakan nama palsu", "Hak menghapus akun medsos", "Hak meminta penghapusan informasi pribadi yang tidak relevan", "Hak anonim di semua platform"], ans: 2, exps: ["Menggunakan nama palsu bukan right to be forgotten.", "Menghapus akun adalah keputusan personal.", "BENAR. Right to be forgotten adalah hak meminta penghapusan informasi pribadi yang tidak relevan dari internet. Diatur UU ITE Pasal 26(3) & UU PDP Pasal 8.", "Hak anonimitas berbeda dari right to be forgotten."] },
    { q: "Dalam kasus phishing (website palsu bank), pasal utama yang dilanggar?", opts: ["Pasal 27", "Pasal 30", "Pasal 35", "Pasal 28"], ans: 2, exps: ["Pasal 27 mengatur konten terlarang, bukan pemalsuan.", "Pasal 30 mengatur akses ilegal, bukan pemalsuan website.", "BENAR. Pasal 35 UU ITE mengatur MANIPULASI/PEMALSUAN informasi elektronik seolah-olah otentik.", "Pasal 28 mengatur berita bohong dan SARA."] },
    { q: "Berapa sanksi maksimal Pasal 36 UU ITE (mengakibatkan kerugian)?", opts: ["6 tahun penjara", "8 tahun penjara", "10 tahun penjara", "12 tahun dan/atau Rp12 miliar"], ans: 3, exps: ["6 tahun bukan sanksi Pasal 36.", "8 tahun bukan sanksi Pasal 36.", "10 tahun bukan sanksi Pasal 36.", "BENAR. Pasal 51 ayat (2): penjara MAKS 12 TAHUN dan/atau denda MAKS Rp12 MILIAR."] },
    { q: "Apa peran BSSN dalam keamanan siber Indonesia?", opts: ["Membuat undang-undang", "Mengadili pelaku", "Koordinasi keamanan siber nasional", "Mengelola database kependudukan"], ans: 2, exps: ["Membuat UU adalah wewenang DPR dan Pemerintah.", "Mengadili adalah wewenang pengadilan.", "BENAR. BSSN berperan mengkoordinasikan keamanan siber nasional, merespons insiden, dan memberikan rekomendasi.", "Database kependudukan dikelola Dukcapil/Kemendagri."] },
    { q: "Pasal 32 UU ITE mengatur tentang apa?", opts: ["Pencemaran nama baik", "Mengubah/memindahkan informasi elektronik", "Penyebaran hoax", "Akses ilegal"], ans: 1, exps: ["Pencemaran nama baik diatur Pasal 27(3).", "BENAR. Pasal 32 mengatur tentang mengubah, menambah, mengurangi, memindahkan, atau menghilangkan informasi elektronik tanpa hak.", "Penyebaran hoax diatur Pasal 28(1).", "Akses ilegal diatur Pasal 30."] },
    { q: "Budapest Convention on Cybercrime adalah?", opts: ["Regulasi EU tentang data", "Konvensi internasional pertama tentang cybercrime", "Perjanjian perdagangan digital", "Standar keamanan NATO"], ans: 1, exps: ["GDPR adalah regulasi EU tentang data pribadi.", "BENAR. Budapest Convention (2001) adalah konvensi internasional pertama tentang kejahatan siber.", "Budapest Convention bukan tentang perdagangan.", "Dibuat oleh Council of Europe, bukan NATO."] },
    { q: "Dalam studi kasus mantan IT staff, pasal apa yang memberikan sanksi terberat?", opts: ["Pasal 30 — 8 tahun", "Pasal 32 — 8 tahun", "Pasal 36 — 12 tahun", "Pasal 322 KUHP — 9 bulan"], ans: 2, exps: ["Pasal 30 maksimal 8 tahun, bukan yang terberat.", "Pasal 32 maksimal 8 tahun.", "BENAR. Pasal 36 UU ITE: 12 tahun penjara dan/atau denda Rp12 miliar karena mengakibatkan kerugian.", "Pasal 322 KUHP hanya 9 bulan."] },
    { q: "Apa prinsip 'consent' dalam UU PDP?", opts: ["Boleh mengumpulkan data tanpa izin", "Pemrosesan data harus dengan persetujuan subjek", "Data boleh dijual ke pihak ketiga", "Consent hanya untuk data sensitif"], ans: 1, exps: ["Tanpa izin justru melangggar prinsip consent.", "BENAR. Prinsip consent berarti data pribadi HANYA boleh diproses dengan persetujuan jelas dari subjek data.", "Penjualan ke pihak ketiga memerlukan consent tambahan.", "Consent diperlukan untuk SEMUA jenis data pribadi."] },
    { q: "Pasal 33 UU ITE mengatur tentang apa?", opts: ["Pencemaran nama baik", "Gangguan terhadap Sistem Elektronik", "Berita bohong", "Pemalsuan informasi"], ans: 1, exps: ["Pencemaran nama baik diatur Pasal 27(3).", "BENAR. Pasal 33 mengatur tindakan yang mengakibatkan gangguan Sistem Elektronik. Contoh: serangan DDoS.", "Berita bohong diatur Pasal 28(1).", "Pemalsuan informasi diatur Pasal 35."] },
    { q: "Apa yang dimaksud dengan DLP (Data Loss Prevention)?", opts: ["Sistem backup data", "Sistem mencegah transfer data tidak sah", "Antivirus server", "Protokol enkripsi"], ans: 1, exps: ["Backup untuk pemulihan, DLP untuk pencegahan kebocoran.", "BENAR. DLP adalah sistem yang mendeteksi dan mencegah transfer data sensitif ke luar organisasi secara tidak sah.", "Antivirus melindungi dari malware, bukan kebocoran data.", "Protokol enkripsi mengamankan data dalam transit."] },
    { q: "Pasal 34 UU ITE mengatur tentang apa?", opts: ["Akses ilegal", "Pemalsuan data", "Memproduksi/menjual perangkat untuk cybercrime", "Penyebaran SARA"], ans: 2, exps: ["Akses ilegal diatur Pasal 30.", "Pemalsuan data diatur Pasal 35.", "BENAR. Pasal 34 mengatur tentang memproduksi, menjual, atau mendistribusikan perangkat untuk memfasilitasi kejahatan cyber.", "SARA diatur Pasal 28(2)."] },
    { q: "Apa perbedaan 'delik biasa' dan 'delik aduan'?", opts: ["Tidak ada perbedaan", "Delik biasa bisa tanpa pengaduan, delik aduan harus ada pengaduan", "Delik biasa lebih berat", "Delik aduan hanya perdata"], ans: 1, exps: ["Ada perbedaan signifikan.", "BENAR. Delik BIASA: polisi bisa menyelidiki TANPA pengaduan. Delik ADUAN: polisi HANYA bisa menyelidiki jika ada pengaduan resmi.", "Berat hukuman tidak ditentukan jenis deliknya.", "Delik aduan bisa pidana maupun perdata."] },
    { q: "Apa yang dimaksud 'chilling effect' dalam hukum cyber?", opts: ["Serangan DDoS", "Deterrence dari hukuman berat", "Ketakutan masyarakat berekspresi karena ancaman hukum", "Dampak virus pada komputer"], ans: 2, exps: ["DDoS bukan chilling effect.", "Deterrence berbeda meskipun berkaitan.", "BENAR. Chilling effect adalah ketakutan masyarakat untuk berekspresi karena ancaman hukum yang berlebihan.", "Virus komputer bukan chilling effect."] },
    { q: "Pasal berapa UUD 1945 menjamin kebebasan berekspresi?", opts: ["Pasal 28A", "Pasal 28E ayat (3)", "Pasal 28G", "Pasal 28J"], ans: 1, exps: ["Pasal 28A mengatur hak untuk hidup.", "BENAR. Pasal 28E ayat (3) menyatakan hak atas kebebasan berserikat, berkumpul, dan mengeluarkan pendapat.", "Pasal 28G mengatur hak perlindungan diri.", "Pasal 28J mengatur pembatasan hak asasi."] },
    { q: "PSE dalam konteks hukum cyber Indonesia adalah?", opts: ["Private Sector Enterprise", "Penyelenggara Sistem Elektronik", "Public Safety Equipment", "Personal Security Encryption"], ans: 1, exps: ["PSE bukan Private Sector Enterprise.", "BENAR. PSE = Penyelenggara Sistem Elektronik, wajib mendaftar ke Kominfo berdasarkan PP 71/2019.", "PSE bukan peralatan keamanan.", "PSE bukan jenis enkripsi."] },
    { q: "Kasus Baiq Nuril Maknun berkaitan dengan pasal apa?", opts: ["Pasal 27 ayat (1) — konten asusila", "Pasal 27 ayat (3) — pencemaran nama baik", "Pasal 30 — akses ilegal", "Pasal 28 — hoax"], ans: 0, exps: ["BENAR. Baiq Nuril dihukum berdasarkan Pasal 27 ayat (1) karena merekam percakapan pelecehan. Ironisnya korban justru dihukum.", "Kasus ini bukan tentang pencemaran nama baik.", "Baiq Nuril tidak melakukan akses ilegal.", "Kasus ini bukan tentang penyebaran hoax."] },
    { q: "Bagaimana Baiq Nuril akhirnya terbebas?", opts: ["Dibebaskan oleh MA", "Mendapat grasi", "Mendapat amnesti dari Presiden", "Kasusnya kadaluarsa"], ans: 2, exps: ["MA justru menghukum Baiq Nuril.", "Grasi mengurangi hukuman, amnesti menghapus tuntutan.", "BENAR. Baiq Nuril mendapat AMNESTI dari Presiden Joko Widodo (2019).", "Kasus tidak kadaluarsa."] },
    { q: "Pasal 52 ayat (3) UU ITE mengatur pemberatan untuk kejahatan terhadap?", opts: ["Anak di bawah umur", "Sistem pemerintah/pelayanan publik", "Kejahatan berulang", "Kejahatan uang besar"], ans: 1, exps: ["Bukan tentang kejahatan terhadap anak.", "BENAR. Pasal 52(3): perbuatan terhadap Sistem Elektronik PEMERINTAH/badan strategis, hukuman ditambah 2/3.", "Residivisme diatur KUHP, bukan Pasal 52(3).", "Besaran uang bukan faktor pemberatan Pasal 52(3)."] },
    { q: "Apa yang dimaksud 'self-regulation' dalam hukum cyber?", opts: ["Pemerintah mengatur semua", "Industri mengatur diri sendiri melalui kebijakan internal", "Pengguna mengatur privasi sendiri", "Pengadilan mengatur interpretasi"], ans: 1, exps: ["Jika pemerintah mengatur semua = command & control.", "BENAR. Self-regulation: industri/platform membuat dan menegakkan aturan sendiri. Contoh: Community Guidelines YouTube.", "Bukan self-regulation dalam konteks hukum.", "Pengadilan bukan bagian self-regulation."] },
    { q: "Pasal 5 ayat (1) UU ITE mengakui apa sebagai alat bukti sah?", opts: ["Hanya surat dan saksi", "Informasi dan dokumen elektronik", "Hanya hasil forensik", "Hanya screenshot"], ans: 1, exps: ["Surat dan saksi adalah bukti konvensional KUHAP.", "BENAR. Pasal 5(1): Informasi Elektronik dan/atau Dokumen Elektronik merupakan alat bukti hukum yang sah.", "Forensik digital adalah metode, bukan bukti itu sendiri.", "Screenshot hanya salah satu bentuk bukti elektronik."] },
    { q: "Berapa lama PSE harus menurunkan konten melanggar hukum menurut PP 71/2019?", opts: ["1 x 24 jam", "4 x 24 jam", "7 x 24 jam", "30 hari"], ans: 1, exps: ["1 x 24 jam bukan ketentuan PP 71/2019.", "BENAR. PP 71/2019 mewajibkan PSE menurunkan konten melanggar hukum dalam 4 x 24 jam.", "7 hari terlalu lama.", "30 hari bukan ketentuan yang berlaku."] },
    { q: "Apa yang dimaksud 'chain of custody' dalam bukti digital?", opts: ["Enkripsi data saat transfer", "Pencatatan kronologis siapa yang akses bukti", "Backup data berkala", "Validasi tanda tangan digital"], ans: 1, exps: ["Enkripsi bukan chain of custody.", "BENAR. Chain of custody: pencatatan kronologis siapa yang mengakses dan mengelola bukti. Jika terputus, bukti bisa ditolak pengadilan.", "Backup bukan chain of custody.", "Tanda tangan digital bukan chain of custody."] },
    { q: "Pasal 28 ayat (2) UU ITE mengatur tentang apa?", opts: ["Berita bohong", "Penyebaran informasi SARA dan kebencian", "Pencemaran nama baik", "Akses ilegal"], ans: 1, exps: ["Berita bohong diatur Pasal 28 ayat (1).", "BENAR. Pasal 28(2) mengatur penyebaran informasi untuk menimbulkan kebencian berdasarkan SARA. Sanksi: maks 6 tahun.", "Pencemaran nama baik diatur Pasal 27(3).", "Akses ilegal diatur Pasal 30."] },
    { q: "Apa yang dimaksud 'restorative justice' dalam revisi UU ITE?", opts: ["Hukuman penjara lebih berat", "Pemulihan hubungan pelaku dan korban", "Denda lebih besar", "Eksekusi lebih cepat"], ans: 1, exps: ["Restorative justice justru menghindari fokus penghukuman.", "BENAR. Restorative justice mengutamakan PEMULIHAN hubungan antara pelaku dan korban melalui mediasi.", "Denda bukan fokus restorative justice.", "Kecepatan eksekusi bukan bagian restorative justice."] },
    { q: "Apa peran DPO (Data Protection Officer) menurut UU PDP?", opts: ["Menghukum pelanggaran data", "Memastikan compliance perlindungan data", "Meretas sistem untuk uji keamanan", "Mengelola server perusahaan"], ans: 1, exps: ["DPO tidak berwenang menghukum.", "BENAR. DPO memastikan organisasi mematuhi regulasi perlindungan data dan menjadi penghubung dengan lembaga pengawas.", "Penetration testing bukan tugas DPO.", "Mengelola server tugas sysadmin."] },
    { q: "GDPR adalah regulasi dari mana?", opts: ["Indonesia", "Amerika Serikat", "Uni Eropa", "PBB"], ans: 2, exps: ["Indonesia memiliki UU PDP.", "AS memiliki CCPA, HIPAA, bukan GDPR.", "BENAR. GDPR (General Data Protection Regulation) adalah regulasi perlindungan data dari UNI EROPA (2018). UU PDP terinspirasi darinya.", "PBB tidak mengeluarkan GDPR."] },
    { q: "Somasi dalam hukum perdata adalah?", opts: ["Laporan polisi", "Surat peringatan resmi sebelum gugatan", "Putusan pengadilan", "Surat dakwaan jaksa"], ans: 1, exps: ["Laporan polisi jalur pidana, bukan somasi.", "BENAR. Somasi adalah surat peringatan/teguran resmi sebagai langkah awal sebelum gugatan perdata.", "Putusan pengadilan hasil sidang.", "Surat dakwaan oleh jaksa jalur pidana."] },
    { q: "Pasal 29 UU ITE mengatur tentang apa?", opts: ["Pencemaran nama baik", "Ancaman kekerasan melalui elektronik", "Berita bohong", "Akses ilegal"], ans: 1, exps: ["Pencemaran nama baik diatur Pasal 27(3).", "BENAR. Pasal 29: ancaman kekerasan atau menakut-nakuti secara pribadi melalui elektronik. Sanksi: maks 12 tahun.", "Berita bohong diatur Pasal 28.", "Akses ilegal diatur Pasal 30."] },
    { q: "Pasal 31 UU ITE mengatur tentang apa?", opts: ["Pencemaran nama baik", "Penyadapan (interception) ilegal", "Pemalsuan data", "Hoax"], ans: 1, exps: ["Pencemaran nama baik diatur Pasal 27(3).", "BENAR. Pasal 31 mengatur larangan penyadapan informasi elektronik milik orang lain. Sanksi: maks 10 tahun.", "Pemalsuan data diatur Pasal 35.", "Hoax diatur Pasal 28(1)."] },
    { q: "Dalam konteks hukum cyber, 'doxing' melanggar pasal apa?", opts: ["Hanya Pasal 27(3)", "Pasal 26 UU ITE + Pasal 65 UU PDP", "Pasal 30 saja", "Tidak ada pasal yang mengatur"], ans: 1, exps: ["Pasal 27(3) hanya salah satu aspek.", "BENAR. Doxing melanggar Pasal 26 UU ITE (data pribadi tanpa consent) dan Pasal 65 UU PDP (mengungkapkan data secara melawan hukum).", "Doxing bukan hanya akses ilegal.", "Ada beberapa pasal yang bisa diterapkan."] },
    { q: "Apa yang harus dilakukan perusahaan PERTAMA jika mantan karyawan masih mengakses sistem?", opts: ["Langsung lapor polisi", "Segera cabut semua akses", "Hubungi media", "Bayar karyawan untuk diam"], ans: 1, exps: ["Lapor polisi penting tapi bukan pertama untuk cegah kerusakan.", "BENAR. Langkah PERTAMA: REVOKE semua akses untuk menghentikan ancaman. Setelah itu kumpulkan bukti dan lapor polisi.", "Media bukan prioritas.", "Membayar untuk diam bisa obstruction of justice."] },
    { q: "Menurut UU ITE Pasal 2, kapan UU ITE berlaku untuk perbuatan di luar Indonesia?", opts: ["Tidak pernah berlaku", "Jika merugikan kepentingan Indonesia", "Hanya jika pelaku WNI", "Hanya jika korban WNI"], ans: 1, exps: ["UU ITE bisa berlaku di luar Indonesia.", "BENAR. Pasal 2: berlaku untuk perbuatan yang MERUGIKAN KEPENTINGAN INDONESIA (effects doctrine).", "Berlaku untuk siapa saja, tidak hanya WNI.", "Bisa berlaku meskipun korban bukan WNI."] },
    { q: "Apa prinsip 'data minimization' dalam UU PDP?", opts: ["Kumpulkan data sebanyak mungkin", "Hanya kumpulkan data yang relevan dan diperlukan", "Hapus semua data setiap hari", "Simpan data format terkecil"], ans: 1, exps: ["Mengumpulkan sebanyak mungkin justru melanggar prinsip ini.", "BENAR. Data minimization: hanya mengumpulkan data yang RELEVAN dan DIPERLUKAN untuk tujuan yang dinyatakan.", "Bukan tentang frekuensi penghapusan.", "Bukan tentang kompresi file."] },
    { q: "Apakah kelalaian perusahaan (tidak cabut akses) menghapus tanggung jawab pidana mantan karyawan?", opts: ["Ya, perusahaan yang salah", "Tidak, kelalaian perusahaan TIDAK menghapus tanggung jawab pidana A", "Ya, pintu tidak dikunci = boleh masuk", "Tergantung hakim"], ans: 1, exps: ["Kelalaian satu pihak tidak menghapus tanggung jawab pihak lain.", "BENAR. A tetap melanggar hukum karena secara hukum sudah TIDAK BERHAK mengakses sistem setelah resign.", "Pintu tidak dikunci bukan pembenaran untuk masuk.", "Prinsip hukumnya jelas, bukan masalah kebijaksanaan hakim."] },
    { q: "UU ITE Pasal 26 mengatur tentang apa?", opts: ["Akses ilegal", "Perlindungan data pribadi dalam sistem elektronik", "Pencemaran nama baik", "Penyebaran hoax"], ans: 1, exps: ["Akses ilegal diatur Pasal 30.", "BENAR. Pasal 26: penggunaan data pribadi melalui media elektronik harus atas persetujuan orang tersebut.", "Pencemaran nama baik diatur Pasal 27(3).", "Hoax diatur Pasal 28(1)."] },
];

for (let i = 0; i < 10; i++) {
    cyberlawTemplates.forEach((template, index) => {
        let variedQuestion = {
            q: template.q + (i === 0 ? "" : ` (Varian Ke-${i})`),
            opts: [...template.opts],
            ans: template.ans,
            exps: [...template.exps]
        };
        
        if (i > 0) {
            let tempOptsMap = [];
            for(let k=0; k<4; k++) {
                tempOptsMap.push({ 
                    text: variedQuestion.opts[k], 
                    expText: variedQuestion.exps[k],
                    isCorrect: (k === template.ans) 
                });
            }
            tempOptsMap.sort(() => Math.random() - 0.5);
            variedQuestion.opts = tempOptsMap.map(op => op.text);
            variedQuestion.exps = tempOptsMap.map(op => op.expText);
            variedQuestion.ans = tempOptsMap.findIndex(op => op.isCorrect);
        }
        if(quiz_cyberlaw.length < 100) {
            quiz_cyberlaw.push(variedQuestion);
        }
    });
}
