const quiz_sna = [];
const snaTemplates = [
    { q: "Apa kepanjangan presisi filosofis dari konsep keamanan terintegrasi DevSecOps?", opts: ["Development, Security, and Operations", "Device Security Optional", "Devised Secure Open Systems", "Development Server Optimization"], ans: 0, exps: ["Konsep fundamental yang menggabungkan laju siklus hidup pengembang kode, staf operasi (deploy), dengan praktikal keamanan tiada henti secara natural.", "Salah. Menandakan opsi sekuritas fisik eksternal, bukan metodologi integrasi pengembangan aplikasi.", "Salah. Akromim manipulatif distraktif semata.", "Salah. Optimization merujuk proses fine-tuning server (Ops), membuang peran wajib pilar Security / keamanan kode."] },
    { q: "Salah satu pilar filosofi paling terkenal di dalam DevSecOps adalah konsep pencegahan berjulukan 'Shift Left', yang memiliki makna...", opts: ["Memindahkan rak server fisik ke sisi sayap keamanan", "Kualitas sekuritas diperhatikan secara sporadis/belakangan", "Mengintegrasikan security seawal mungkin ke pangkal pertama (awal) dalam siklus SDLC / fase Code", "Menghapus perlindungan usang yang tak kompatibel"], ans: 2, exps: ["Salah. Tidak berhubungan dengan operasional perangkat hardware di Data Center.", "Salah. Hal ini justru bertentangan dengan pendekatan 'silo' IT klasik yang selalu melakukan pentest HANYA sesaat memasuk fase rilis final.", "Melakukan pengujian injeksi awal di mesin lokal programmer itu sendiri sebelum menjadi beban raksasa jika cacat tembus tertanam sampai arsitektur production.", "Salah. Shift Left tak bersinggungan langsung dengan penghapusan aturan, ini adalah prioritas peletakan workflow lini masa (kiri=awal)."] },
    { q: "Alat pengujian security dinamis (DAST) lebih superior dan berbeda dengan saudara kodenya (SAST) terutama karena:", opts: ["Hanya melihat baris kode tekstual dari IDE tanpa dijalankan", "Memeriksa aplikasi secara nyata (live deployment berjalan) mensimulasikan injeksi data peretas dari port HTTP", "Meneliti library third-party lawas di package json", "Memblokir IP peretas DDOS secara manual"], ans: 1, exps: ["Salah. SAST (Static) bertugas melihat source code telanjang kaku (Text Analysis/AST), tanpa environment aktif.", "DAST (Dynamic) bermain pada lingkup interaktif aplikasi web layaknya user menembakkan fuzzing payload SQL (seperti Zap).", "Salah. Proses analisis versi usang dependency library pihak luar dinamakan murni SCA (Software Composition Analysis).", "Salah. Konfigurasi mitigasi perlindungan perimeter paket masuk dan keluar diemban utuh oleh WAF maupun IPS/IDS."] },
    { q: "Sebuah sistem pengelola Log keamanan jaringan terpusat mumpuni yang memeriksa keanehan trafik lintas node berdasarkan correlation rules untuk mencium insiden adalah...", opts: ["DNS Node Proxy", "SIEM (Security Information and Event Management)", "Git Version Control", "Docker Log Server"], ans: 1, exps: ["Salah. DNS Proxy bertindak menopang jembatan penamaan alamat jaringan keluar internet / cache resolve.", "SIEM menghimpun log aplikasi, server, IDS/IPS dan mendeteksi korelasi unik layaknya intel untuk memperingatkan anomali.", "Salah. Git hanya membukukan histori kontrol file source project programmer sembari melacak revert, tak ada hubungannya dengan deteksi heking traffic realtime.", "Salah. Log dalam docker hanyalah catatan stdout mesin semata, belum termasuk kecerdasan agregasi threat intelligence SIEM."] },
    { q: "Keistimewaan Docker dibanding Virtual Machine Lawas adalah konsep 'Containerization'. Pada lingkungan Docker itu, isolasi ditekankan ke taraf...", opts: ["Virtualisasi Hardware BIOS yang berat sepenuhnya", "Proses isolasi tingkatan level OS (berbagai aplikasi berbagi 1 Kernel bapak yang sama secara efisien)", "Simulasi kartu grafis / GPU", "Penumpukan RAM Fisik statis individual"], ans: 1, exps: ["Salah. VM memakan memory raksasa wajib dengan OS full per tiap Guest VM di atas hypervisor rakus.", "Docker container hanya mengepaki library & dependency unik, tak butuh OS terpisah baru asalkan menggunakan Linux kernel bersama, start jauh lebih kilat.", "Salah. Konteks rendering hardware interface tidak merepresentasikan efisiensi kontainer.", "Salah. Docker justru sanggup berbagi memory idle Host secara elastik alih alih memesan RAM pasti (statis) seperti pola VirtualBox/VMWare lawas."] },
    { q: "Manakah sebuah pendekatan di mana infrastruktur server dibangun, dikontrol, serta dihancurkan sepenuhnya lewat barisan script logis layaknya sistem kode program?", opts: ["Software Defined Data Center Firewall", "Infrastructure as Code (IaC)", "Platform as a Service Virtualization", "Remote Database Command Prompt"], ans: 1, exps: ["Salah. Lebih menjurus ke manipulasi paket jaringan ketimbang pembangunan instans mesin utuh.", "IaC (seperti Terraform) mengeksekusi arsitektur dan resource raksasa dari penyedia cloud berdasarkan definisi bahasa skrip deklaratif layaknya .yml file re-runable.", "Salah. IaC bukan PaaS yang mana lingkup runtime terberi otomatis, namun abstraksi kendali manual dari IaaS provider.", "Salah. Itu merupakan kegiatan memanipulasi baris cell SQL via klien terminal sederhana, tak mengarsiteki sistem host."] },
    { q: "Teknik Security Monitoring ofensif proaktif di mana server palsu terisolasi atau jebakan celah diekspos paksa ke luar untuk memancing dan mempelajari serangan hacker asli disebut...", opts: ["Blackhole Spoofing Traffic", "Honeypot", "DDoS TCP Mitigation", "Load Balancer Dropping"], ans: 1, exps: ["Salah. Blackhole merutekan trafik mampat tak bersalah serta jahat ke alamat fiktif nir-respon untuk menahan serangan botnet.", "Honeypot merupakam kuali manis untuk pengalihan musuh (Decoy) yang merekam pergerakan eksploit mereka secara eksklusif bagi pemantau lab SIEM.", "Salah. Mitigasi proteksi DDoS lebih mirip tameng filter ketimbang simulasi kotak mangsa / server umpan.", "Salah. Load Balancer bertugas membagi porsi beban pelanggan/klien seimbang ke pelbagai server produksi."] },
    { q: "Perbedaan kunci fungsional utama yang drastis antara IDS (Intrusion Detection) dan IPS (Intrusion Prevention) di level lalu lintas paket adalah...", opts: ["IPS difokuskan hanya untuk server cloud Windows", "IDS sanggup bertindak agresif memblok serangan; IPS pasif pasrah", "IDS mendeteksi & dan menyalakan bel (Alert Logs) murni namun pasif, IPS jauh agresif merobohkan dan memotong koneksi serangan", "IDS menangani database IPS di router wireless rumahan"], ans: 2, exps: ["Salah. Keduanya beroperasi buta platform, universal lintas protokol IP OSI model independen.", "Salah terbalik! IPS Prevention (Prevent/Cegah), sementara IDS (Detect/Mendeteksi-pasif).", "Pendekatan IDS menaruh sensor bel alarm di persimpangan, sedang IPS seperti Polisi pencegat yang menge-DROP paket ancaman langsung dari rule port engine (Firewall gabungan).", "Salah. Mereka difokuskan mengatasi server datacenter jaringan skala enterprise."] },
    { q: "Prinsip dasar mendesain IT Sistem agar selalu memberikan kewenangan perizinan semata-mata paling minimum khusus sebatas hak fungsionalnya saja menaati prinsip...", opts: ["Redundancy Overloading", "Principle of Least Privilege", "Symmetric Cryptography Bypass", "Role Base Administration Unification"], ans: 1, exps: ["Salah. Menyangkut desain pertahanan mesin darurat duplikat dari kehancuran listrik semata.", "Least Privilege menutup celah pergerakan horizontal mematikan hacker bila akun standar ditembus. Tak boleh beri User hak Root jika hanya butuh hak Edit.", "Salah. Kripotgrafi menyoal kalkulasi enkripsi simetris matematik, tak ada campur tangan otoritas role admin jaringan.", "Salah. RBAC mendefinisi grup, namun konsep spesifik hak terkecil wajib ada di pilar Least Privilege."] },
    { q: "Langkah mendasar melangsungkan ketahanan kuat sebuah server rentan ke internet bebas (Server Hardening) mutlak wajib...", opts: ["Membiarkan port Telnet kuno terbuka luas bebas otentikasi", "Melimitasi kata sandi panjang mudah agar hapalan lebih mulus", "Menutup mutlak semua celah port terbengkalai serta memberlakukan auto patching eksploit di level OS Kernel", "Memasang jaringan ter-routing ke area publik komersial Wi-Fi terdekat"], ans: 2, exps: ["Salah. Protokol Telnet rawan intersepsi plain text sniffer oleh siapapun pendengar switch hub.", "Salah. Kompleksitas otentikasi adalah pertahanan terdepan *bruteforce* remote, semakin sepele rentan ditembak mati bot.", "Mengecilkan *Attack Surface* dari luar dengan Firewalld serta menambal celah rentan OS / Patch Management adalah inti proses Hardening Server murni.", "Salah. Merupakan kejahatan standar eksposure area terlarang bila produksi bersentuhan lanskap tak terkendali Wi-Fi lokal komersial."] }
];

for (let i = 0; i < 10; i++) {
    snaTemplates.forEach((template, index) => {
        let variedQuestion = {
            q: template.q + (i === 0 ? "" : ` (Varian Ke-${i})`),
            opts: [...template.opts],
            ans: template.ans,
            exps: [...template.exps]
        };
        
        if (i > 0) {
            let tempOptsMap = [];
            for(let k=0; k<4; k++) {
                tempOptsMap.push({ 
                    text: variedQuestion.opts[k], 
                    expText: variedQuestion.exps[k],
                    isCorrect: (k === template.ans) 
                });
            }
            tempOptsMap.sort(() => Math.random() - 0.5);
            variedQuestion.opts = tempOptsMap.map(op => op.text);
            variedQuestion.exps = tempOptsMap.map(op => op.expText);
            variedQuestion.ans = tempOptsMap.findIndex(op => op.isCorrect);
        }
        if(quiz_sna.length < 100) {
            quiz_sna.push(variedQuestion);
        }
    });
}
