const quiz_softsec = [];
const softsecTemplates = [
    { q: "Apa tujuan utama nan vital melakukan sesi Threat Modeling di usia awal sebuah fase Desain Software?", opts: ["Menghitung total baris estimasi kode akhir", "Mengidentifikasi vektor kerentanan sedini masa cetak biru, mengevaluasi potensi peretasan, dan meredam ke titik aman via kontrol teoretis", "Menjalankan kompilator kode Unit Test otomasi ganda", "Pelatihan Use Case pengetikan skenario UML Actor semata"], ans: 1, exps: ["Salah. Itu adalah fungsi evaluasi LoC metrik proyek.", "Aktivitas proaktif mencari kelemahan (find bugs in design) sebelum sebaitpun kode ditulis, menghindarkan malapetaka ongkos perbaikan fatal di akhir waktu rilis.", "Salah. Penulisan test dilakukan mandiri paska penulisan komponen terkecil di SDLC berjalan.", "Salah. Pemetaan skenario murni Use Case kurang berfokus pada mitigasi celah keamanan."] },
    { q: "Metode pemodelan berbasis alur diagram arah grafis yang merangkum Entitas, Proses (Lingkaran), Penyimpanan (Garis Ganda), demi membedah rentan tidaknya sistem secara logikal disebut...", opts: ["Activity Routing Diagram", "Use Case State Diagram", "Data Flow Diagram (DFD)", "Gantt Project Chart"], ans: 2, exps: ["Salah. Lebih menjelaskan urutan kejadian if-else keputusan fungsi.", "Salah. Hanya mencerap wujud pengguna fungsional (Aktor).", "DFD sangat dianjurkan untuk model ancaman, ia memetakan persimpangan jalur pertukaran objek sensitif melintasi Trust Boundary (Garis Putus-putus Kepercayaan).", "Salah. Grafik Gantt hanya mengatur lini waktu pengumpulan jadwal proyek."] },
    { q: "Metodologi STRIDE dipelopori keamanan mikroskopis tim korporasi Windows. Huruf 'S' menandakan klasifikasi serangan...", opts: ["Spoofing", "Scripting", "Spraying", "Scanning"], ans: 0, exps: ["S - Spoofing adalah teknik manipulatif peniru identitas atau hak masuk pengguna resmi untuk menipu pangkalan otentikasi login seakan dari sosok sah.", "Salah. Scripting mengarah ke vektor alat eksploit peretasan Cross-site, tidak masuk akronim murni di STRIDE Microsoft.", "Salah. Spraying berkaitan aksi Password menebak beruntun horizontal tapi nama kaidahnya tak masuk.", "Salah. Scanning lebih masuk sebagai fase tahapan reconnaisance pengumpulan pentest di awal mula."] },
    { q: "Aksi Tampering pada rentetan pilar perlindungan STRIDE mengindikasikan upaya bahaya tentang...", opts: ["Pura-pura (menyamar menjadi orang tak berdosa bertransaksi palsu)", "Membocorkan letak server asimetris rahasia di internet nirkabel", "Aksi memodifikasi payload / memanipulasi integritas data transaksi pada jalur sistem tanpa wewenang otorisasi", "Menutup alur pertolongan kelistrikan pangkalan"], ans: 2, exps: ["Salah. Menyaru jadi sosok sah murni merupakan cakupan serangan (S) Spoofing.", "Salah. Eksfiltrasi sandi kebocoran data masuk di kotak bahaya (I) Information Disclosure.", "Tampering (Merusak/Mengacak-acak) berfokus merobek tameng Integrity (Integritas Asli). Hacker melukai logika data utuh sebelum sampai ke Storage.", "Salah. Membuat lumpuh alur trafik server secara fatal merujuk pada pilar eksploit (D) Denial of Service."] },
    { q: "Pelanggaran Repudiation dalam kelompok ancaman keamanan ancaman STRIDE, mereferensikan kepada perilaku licik pengguna...", opts: ["Menyangkal atau lepas tangan terbukti secara teknis seakan tidak pernah melempar instruksi (aksi tindakan fiktif di dalam jejak audit statis log tak memadai)", "Gagal otentikasi biometrik berturut-turut lantas kabur dari network IDS", "Mencegah database server hidup dari beban komputasi besar paksa", "Pencurian identitas MAC Address demi mengelabui VLAN"], ans: 0, exps: ["R - Repudiation membiarkan tersangka menyangkal perbuatannya 'Bukan saya yang mentransfer dana sejuta itu!' karena si programmer gagal menancapkan sistem Audit Trail / Log Anti-manipulasi (Non-Repudiation) handal.", "Salah. Terblokir di pintu keluar tak menyangkut penangkalan klaim pasca instruksi berhasil di eksekusi mesin inti.", "Salah. Meluluhlantakkan respon komputer dari overload sangat erat hubunganya eksklusif di DoS murni.", "Salah. Manipulasi wujud paket agar menyaru milik peranti network tertentu murni jatuhnya ke (S) MAC Spoofing."] },
    { q: "Bila mana sistem kehilangan asuransi dan ketersediaan jejak log (Audit Trails) solid, tindakan pengguna nakal lolos akibat gagal membungkam ancaman tipe serangan...", opts: ["Information Disclosure", "Elevation of Privilege", "Repudiation", "Spoofing"], ans: 2, exps: ["Salah. Ekstraksi data privasi pasif membawahkan domain Confidentiality.", "Salah. Meningkatan daya gedor akun rendah ke Admin masuk ruang lingkup pilar E dari singkatan akronim.", "Bila rekam jejak digital valid tidak aman di-tweak log-nya, penyangkalan Repudiation bebas merajalela membuat pelakunya imun hukum persidangan digital forensics.", "Salah. Pemalsuan klaim akun asli lebih menitikberatkan pengelabuan wujud identitas otentik login."] },
    { q: "Kategori ancaman Information Disclosure (Sifat Bocor Data Paksa) di kerangka konsep STRIDE mengotori mandat pilar utama hukum IT Keamanan (CIA Triad) secara vulgar yaitu:", opts: ["Integrity", "Confidentiality", "Availability", "Non-repudiation"], ans: 1, exps: ["Salah. Syarat Integritas lebih terancam dari taktik sabotase manipulasi (Tampering/Edit Data secara ilegal paksa).", "Kerahasiaan data private yang terenkripsi dan khusus (Confidentiality) hancur ketika database dibocorkan dan disebar bebas paksa (Information Disclosure).", "Salah. Domain uptime online (Availability) dirusak oleh vektor gempuran DDoS Denial of Service berlarut larut.", "Salah. Mekanisme ini dibongkar oleh aksi peniruan (Spoofing) maupun Repudiasi transaksi palsu masa lampau."] },
    { q: "Elevation of Privilege (E) mengejawantahkan kelakuan vektor penyerangan kritis manakala si oknum...", opts: ["Penyerang membobol gembok besi ruang perakitan server datacenter", "Pengguna tamu (biasa) mengeksploitasi cacat miskonfigurasi Kernel OS sembari menyedot akses mutlak setara akun Root lokal", "Sistem kolaps gara-gara pengeroyokan request paksa koneksi dari zombie server berjamaah", "Pihak awam secara insidental mendapati alamat hash sandi publik transparan terekspos"], ans: 1, exps: ["Salah. Itu penembusan pertahanan Perimeter Fisik.", "Eskalasi hak wewenang menembus sekat pengguna remeh (Guest) meloncat paksa mengkudeta izin Admin (Root/System) pada piranti sasaran mutlaknya dinamakan Elevation/Escalation.", "Salah. Praktik lumpuhnya servis pelayanan web tersebut memvalidasi kelakuan dari kategori DDoS (D).", "Salah. Tersajinya akses lihat pasif atas data krusial terjatuh pada lembah Information Disclosure rawan."] },
    { q: "Mekanisme DREAD memiliki formulasi kuantifikasi murni matematis dengan fungsi utamanya buat...", opts: ["Menimbang rasio sewa infrastruktur Cloud", "Mengalkulasi pemeringkatan Prioritas / Risk Severity dari aneka skenario celah kejelekan berdasar impak dan frekuensi secara matematis tegas (Skor 0-10)", "Mensistematisasi fase model pemrograman konvensional ala Waterfall klasik usang", "Memetakan topologi firewall kabel LAN C++ router edge cloud deployment"], ans: 1, exps: ["Salah. Kurang mengusik sisi proteksi keamanan perangkat program logikal maya melainkan budget korporasi.", "Mendapatkan rating (Average Score). Misal ancaman X punya Damage 10, Reproducibility 10, dll otomatis disimpulkan sangat BERBAHAYA dibanding ancaman skor 3 rendahnya DREAD.", "Salah. SDLC tidak disetir dari hasil numerik metrik resiko eksekusi.", "Salah. Desain instalasi alat jaringan jauh bertentangan dengan fungsionalitas DREAD menilai level keparahan bobot ancaman."] },
    { q: "Dalam jajaran DREAD, parameter 'Reproducibility' (Keterulangan) khusus menilai tentang hal...", opts: ["Tempo kelajuan produksi patch kode pembuat", "Mudahkah suatu serangan/kerentanan tersebut dipicu ulang menembus berkali-kali (di-reproduksi) di lingkungan stabil konsisten secara identik presisi seragam di mana parameter tetap akurat telak eksak valid", "Pengulangan dokumentasi bug IT yang tidak efisien dari tiket support logis tumpang tindih beruntun di pelaporan Jira", "Pendeteksian virus usang dari kloning peretas tak bersisa usai dieksekusi"], ans: 1, exps: ["Salah. Tidak memfaktorkan durasi pemrograman teknikal dev.", "Bila eksploit butuh waktu langka spesifik (Timing race condition ajaib) skornya rendah (Sulit Reproducible). Jika gampang di-copy paste skrip oleh script kiddie jam berapa pun skor akan mentok sangat mematikan tinggi penuh di kalkulasi Reproducibility 10 skor absolut.", "Salah. Manajemen duplikat keluhan pelanggan (Bug Triage) jauh berbeda murni dari metrik skor bahaya serangan ulang peretas ancaman resiko absolut komputasi algoritmik fana statis absolut dinamis valid eksak.", "Salah. Hal deteksi mesin tak direpresetasikan eksak pada skor kerentanan statis seragam."] }
];

for (let i = 0; i < 10; i++) {
    softsecTemplates.forEach((template, index) => {
        let variedQuestion = {
            q: template.q + (i === 0 ? "" : ` (Varian Ke-${i})`),
            opts: [...template.opts],
            ans: template.ans,
            exps: [...template.exps]
        };
        
        if (i > 0) {
            let tempOptsMap = [];
            for(let k=0; k<4; k++) {
                tempOptsMap.push({ 
                    text: variedQuestion.opts[k], 
                    expText: variedQuestion.exps[k],
                    isCorrect: (k === template.ans) 
                });
            }
            tempOptsMap.sort(() => Math.random() - 0.5);
            variedQuestion.opts = tempOptsMap.map(op => op.text);
            variedQuestion.exps = tempOptsMap.map(op => op.expText);
            variedQuestion.ans = tempOptsMap.findIndex(op => op.isCorrect);
        }
        if(quiz_softsec.length < 100) {
            quiz_softsec.push(variedQuestion);
        }
    });
}
