const quiz_sofeng = [];
const sofengTemplates = [
    { q: "Apa definisi murni dari Software Engineering menurut rumusan IEEE secara presisi teknikal?", opts: ["Proses membuat kode manual", "Aplikasi pendekatan sistematis, disiplin, dan terukur terhadap pengembangan, pengoperasian software", "Pabrikasi siklus hardware dan modul mikrokontroler utuh", "Pencadangan file komputer"], ans: 1, exps: ["Salah. Membuat kode hanyalah fase konstruksi belaka dari sistem, tak mencakup engineering holistik.", "Tepat! Ia menekankan pada metode kuantitatif yang metodis dan terukur alih-alih coding liar ala koboi tanpa spesifikasi berdisiplin (Systematic & Quantifiable approach).", "Salah. Software berfokus pada benda logikal maya (Logic Entity) ketimbang manufaktur pabrik hardware nyata aus fisik.", "Salah. Hanya rutinitas administratif operasional IT pendukung."] },
    { q: "Manakah ciri yang otentik menjadi karakteristik eksistensi 'Software' bila disandingkan berseberangan dengan entitas 'Hardware' kaku konvensional?", opts: ["Software akan memicu keausan perlahan dari waktu ke waktu karena terik matahari", "Software dikembangkan pelan (engineered), bukan dicetak pabrikasi secara massal kaku", "Punya batas waktu umur baterai", "Tergantung komponen standar mati"], ans: 1, exps: ["Salah. Software itu immortal/kebal thd gesekan mekanik, kegagalan fisik mustahil merobohkannya.", "Hardware dicetak pabrik sekali jalan. Software direkayasa ulang logika susunannya menyesuaikan fitur secara lentur lewat pola siklus Engineering SDLC yang bertumbuh.", "Salah. Hardware murni yang dihidupkan dengan daya tegangan eksternal semata yang haus energi voltase nyata.", "Salah. Kode peranti lunak umumnya dirancang murni secara pesanan (Custom built) dari nol (logic scratch build)."] },
    { q: "Pada rincian 4 pilar lapisan piramida (Layers) dalam disiplin Software Engineering baku, pondasi inti yang bertugas memastikan semuanya berjalan terukur adalah...", opts: ["Process", "Methods", "Quality Focus", "Tools"], ans: 2, exps: ["Salah. Proses membangun manajemen kerangka kerja proyek secara hierarkis pengiriman (Delivery Framework).", "Salah. Method merupakan taktik teknis/aturan spesifik dari sisi 'How To' merancang UML atau test case spesifik unit test modular.", "Semua teknik dan skenario yang dijalankan tim harus menjunjung akar kualitas yang absolut dan utuh (Kualitas = Basis Fondasi SE murni sejati).", "Salah. Tools hanyalah kakas pengotomasian fasilitator mekanis IDE pendukung semata (contoh: VCS Git, Kompilator C)."] },
    { q: "Kerangka Metodologi Agile menitikberatkan manifesto nilai utama fleksibilitas kecepatan tim yang mendobrak doktrin lawas prosedural dengan memegang teguh pedoman bahwa...", opts: ["Individu dan interaksinya BUKAN prioritas, yang penting mesin berjalan otomatis total sendirinya memuntahkan program utuh", "Menerima (Welcome) perubahan requirement kapapun meski sangat krusal telat di ujung akhir delivery asalkan pelanggan puas kompetitif nilainya", "Software boleh bug asalkan cepat selesai perikatan negosiasinya tebal hitam diatas kertas kontrak mati", "Customer dilarang keras campur tanggan mengubah arah haluan proses berjalan sampai proyek usai"], ans: 1, exps: ["Salah. Manifesto ke-1 secara spesifik menyanjung 'Individu dan interaksi di atas alat proses' mati.", "Prinsip ke-2 menegaskan: Agility memanfaatkan kelincahan banting setir perubahan mendadak demi mendulang laba competitive advantage untuk user walau tenggat waktu menipis murni.", "Salah. Dokumentasi ekstensif diganti iterasi nyata (Working Software) dan kontrak tegas direduksi demi kolaborasi murni erat transparan mutual dinamis natural.", "Salah. Klien harus selalu ditemani / di-cc rapat koordinasi rutin daily sepanjang nafas fase development murni SDLC terjalin nyata natural."] },
    { q: "Dalam kerangka kerja (Framework) empiris Scrum murni asuhan Sutherland & Schwaber standar, durasi spesifik batas waktu untuk rapat perbincangan harian (Daily Stand-up) tak boleh melebihi aturan emas durasi...", opts: ["15 Menit mutlak maksimal berdiri konstan statis", "3 Jam perundingan serius teknis modifikasi algoritma detail pelik di ruang direktur eksekutif rapat harian", "Bergantung suasana hati manajer tim tak ada ikatan kaku dinamis", "Sampai bug selesai semuanya di hari itu mutlak sempurna tak boleh ada interupsi"], ans: 0, exps: ["Daily Scrum adalah ajang sinkronisasi cepat (Time-boxed) 15-minute event. Mengapa sambil berdiri? Agar developer tidak terbawa mengulur rapat bahas masalah kepanjangan yang mematikan arus ritme coding produktif pagi hari murni dinamis rutinitas.", "Salah. Kalau rapat 3 jam itu jatuhnya Planning Session Sprint murni.", "Salah. Terikat pada pedoman Scrum Guide baku.", "Salah. Ini sekedar ajang berbagi laporan 'Apa yg kukerjakan kemarin', 'Apa hari ini', dan 'Ada hambatan?'. Solusi dicari pasca stand-up meeting usai terpisah!"] },
    { q: "Peran fungsional krusial manakah sbg penjaga gawang yang menaksir angka profitabilitas investasi (ROI) sekaligus prioritas tunggal daftar pengerjaan utuh (Backlog) proyek produk akhir dalam ranah tim Scrum independen?", opts: ["Scrum Master", "Developer / Programer Eksekutif Back-End Senior CTO Chief Architect", "Product Owner (Sponsor Bisnis Tunggal/Representasi Kuat Pelanggan)", "Stakeholder Pasif Eksternal Konsultan Investor Luar Publik User Anonim Publik Universal Global Network Eksternal Mutlak"], ans: 2, exps: ["Salah. SM bukan bos memerintah fitur bisnis, ia sekadar fasilitator murni 'Servant-leader' pembuka rintang jalan tol murni pemecah ganjalan emosi blokir teknis team developer.", "Salah. Dev bebas otonom menafsir 'Bagaimana' (How) merakit kodenya teknis, tap tak melegitimasi arah angin produk 'Apa' (What) yang hendak dijual komersil murni pasar raya.", "PO adalah bos otoritatif tunggal wakil telak stakeholder berkewajiban meramu/menata hirarki spesifikasi barang (Menguasai THE WHAT of backlog fitur prioritas nilai niaga ekonomis matang murni kompetitif ROI).", "Salah. Klien cuma penyumbang usul pasif eksternal lewat pintu PO tak berhak acak-acak Sprint di dalam berjalannya masa."] },
    { q: "Apa nama konsep dalam Scrum yang dipakai secara historikal dinamis sbg tolak ukur kecepatan tim dalam mencerna kuantitas bongkaran bobot Story Point tuntas fungsional selesai mutlak pada setiap blok Sprint demi Sprint berjalannya waku?", opts: ["Speed Meter Konstan Linear Algoritma Statis Baku Estimasi Kasar Parameter Prediktabel Statis Rata-rata Kaku Absolute Universal Kecepatan Programmer", "Velocity (Velositas Murni Empiris Riil Laju Produksi Tuntas Historikal Dinamis Konstan Parameter Fleksibel Terbuka)", "Milestone Tracking Absolut Statis Rigid Deadline Mutlak Tekanan Harian", "Story Track Path Jalur Mutlak Perintah Mandat Atasan Hierarkis Otoriter Baku Tetap Abadi Waktu Target Beban Harian"], ans: 1, exps: ["Salah. Tidak ada rumus statis kecepatan mesin seragam programmer absolut seragam fana statis absolut dinamis valid eksak.", "Tepat! Velocity didapat diujung Sprint dengan menghitung total angka Fibonacci riil (story points) pada seluruh task yang statusnya lunas tuntas teruji 'Done'. Rata-rata ini memprediksi volume kuat komitmen Sprint ke depannya terukur rasional transparan.", "Salah. Melenceng ke metode usang lawas Milestone Tracking statik.", "Salah. Manajemen duplikat tekanan paksa tak searah alur sprint lincah."] },
    { q: "Di aspek Desain Arsitektur Sistem, Tipe Cohesion manakah yang dipandang paling agamis, suci murni bersinar mutlak terbaik ideal paripurna, tatkala sebuah modul/elemen kompak utuh berkontribusi eksklusif tunggal hanya buat menuntaskan 1 kewajiban proses spesifik bulat absolut tunggal terisolasi rapi murni logikal padat fungsional tuntas terukur presisi?", opts: ["Logical Cohesion Ambigu Abstrak Variabel Dinamis Universal Terbuka Bebas Statis Fleksibel Rela", "Functional Cohesion (Kohesi Fungsional Padu Tunggal Murni Isolasi Kuat Solid Fokus Tajam Target Fungsional)", "Coincidental Cohesion Berantakan Semrawut Acak Logis Tercampur Baur Sampah Eksekusi Abstrak Gado-gado Modularitas Hancur", "Temporal Cohesion Sinkron Waktu Paralel Eksklusif Dinamis Asinkron Tunggu Eksekusi Terburu-buru Sinkron Waktu Mutlak Linear Waktu Sejalan Asinkron Eksklusif Dinamis"], ans: 1, exps: ["Salah. Logical sekadar kelompok fungsional kasta bawah (seperti Modul yg khusus menampung kumpulan function validasi password dicampur function validasi email krn secara nalar 'mirip').", "Benar! Kohesi ini bak ksatria suci di mana modul X misal fungsi khusus spesifik tajam CalculateTax() tak merangkap campur baur ke urusan print slip bayar murni. (Highest Cohesion).", "Salah. Kohesi terburuk semrawut tanpa benang merah sama sekali kebetulan masuk folder sama.", "Salah. Kohesi Temporal sekadar tergabung lantaran fungsi-fungsi tsb melintas dikala durasi eksekusi saat server boot up statis mutlak bersamaan harian rutin fungsional waktu berjalan."] },
    { q: "Konsep pemisahan arsitektur SOLID, di sisi huruf kembar keadilan 'S' menyiratkan ide Single Responsibility Principle. Artinya apa kelak menimpa struktur abstraksi objek class di sistem kelak...", opts: ["Class dilarang merangkap jabatan, hanya dirancang lahir punya 1 dalih absolut murni (satu alasan tunggal) kelak bilamana hendak direvisi/diubah fungsionalitasnya utuh mandiri tunggal tertutup absolut", "Class wajib terbebas tanggungan fungsional nol murni lepas eksekusi mati pasif", "Tidak ada error, cuma lebih cepat saja mutlak performansi murni", "Class wajib merangkap ganda gempuran seluruh fungsional program UI, DB, Network sekaligus demi kesatuan hemat letak memori hardisk tunggal eksekusi kompak lebur satu tempat absolut statis"], ans: 0, exps: ["Setepatnya ini! (A Class Should Have Only One Reason to Change) Jika ia kelas ReportGenerator, jika UI format printout mau diganti, ya wajar dirubah. Tapi ia tak boleh dirubah manakala URL database dipindah, karena itu job konektor DB! Mencegah god object spagheti code yang kusut menggerogoti stabilitas rilis fitur depan kelak mutlak sempurna fungsional.", "Salah. Pemogokan class absurd merusak siklus jalan komputasi murni logika bisnis objektif universal komputasi eksak fana fungsional eksekusi OOP abstrak mutlak hirarkis transparan.", "Salah. BUKAN urusan run-time latency, malah membidik kemudahan baca manusia dan cegah letup domino efek bug waktu modifikasi murni.", "Salah. Malah sengaja dikumpulkan jd 'God Anti-Pattern' paling mematikan di desain kopling kencang buruk murni struktural."] },
    { q: "UML diagram yang memiliki wujud paling menyerupai gaya flow-chart pemrograman usang klasik dengan deret kotak keputusan logic terstruktur dan panah proses murni alur percabangan statis logika sekuensial paralel runtut asinkron adalah diagram...", opts: ["Class Diagram", "Sequence Diagram", "Use Case Diagram", "Activity Diagram"], ans: 3, exps: ["Salah. Menunjukkan benda-benda arsitektur Blueprint rancang cetak benda nyata properti atribut.", "Salah. Model pesanan pesan beruntun interaksi rentan waktu sejalan.", "Salah. Pemetaan bulat aktor statis hak akses.", "Benar. UML mendesain Activity melengkungkan aksi logika sistem flow-chart belah ketupat keputusan aksi asinkron pararel sekuensial tuntas murni logikal transparan transisi eksak komputasi."] }
];

for (let i = 0; i < 10; i++) {
    sofengTemplates.forEach((template, index) => {
        let variedQuestion = {
            q: template.q + (i === 0 ? "" : ` (Varian Ke-${i})`),
            opts: [...template.opts],
            ans: template.ans,
            exps: [...template.exps]
        };
        
        if (i > 0) {
            let tempOptsMap = [];
            for(let k=0; k<4; k++) {
                tempOptsMap.push({ 
                    text: variedQuestion.opts[k], 
                    expText: variedQuestion.exps[k],
                    isCorrect: (k === template.ans) 
                });
            }
            tempOptsMap.sort(() => Math.random() - 0.5);
            variedQuestion.opts = tempOptsMap.map(op => op.text);
            variedQuestion.exps = tempOptsMap.map(op => op.expText);
            variedQuestion.ans = tempOptsMap.findIndex(op => op.isCorrect);
        }
        if(quiz_sofeng.length < 100) {
            quiz_sofeng.push(variedQuestion);
        }
    });
}
